### ISSUE TITLE
FileNotFoundError: Reference genome not supported!

### ISSUE THREAD

**Issue by BlackPianoCat** [dmcbffeng/StripeCaller#5]
So I am trying to run `stripe_caller_all()` and import either the file `h38` from your repository, or `GRCh38_full_analysis_set_plus_decoy_hla.fa` from [1000 genomes](https://www.internationalgenome.org/). It always shows me this `FileNotFoundError`.

I call the function like that:
```python
  stripe_caller_all(
          hic_file='/mnt/raid/Spring/Stripes/stripes_data/ChIADrop_JAXGM/ChIA-PET_hg38_GM12878_Cohesin_LHG0051H_0104V_pooled_pairs.hic',
          reference_genome='caller/reference_genome/hg38',
          chromosomes=['chr21'],
          output_file='/mnt/raid/Spring/Stripes/stripes_data/ChIADrop_JAXGM/ChIA-PET_hg38_GM12878_Cohesin_stripes.txt',
          norm='balanced',
          threshold=0.01,
          max_range=150000, resolution=1000,
          min_length=30000, min_distance=50000,
          stripe_width=1, merge=1, window_size=8
  )
```

**Edit:**  _Just the correct reference_genome that should be used._

**Comment by seanpatrickmoran** [comment]
if you call it from a python shell or notebook, I had the same issue. I feel this happens as it is intended to be called as a CLI-application.

I get around this by overwriting "load_chrom_sizes()" to the following:

```
def load_chrom_sizes(reference_genome):
    """
    Load chromosome sizes for a reference genome
    """
    my_path = os.path.abspath(os.path.dirname(os.getcwd())) #jupyter notebook mode...
    # rg_path = f'{my_path}/reference_genome/{reference_genome}'
    rg_path = f'{my_path}/{reference_genome}'
    f = open(rg_path)
    lengths = {}
    for line in f:
        [ch, l] = line.strip().split()
        lengths[ch] = int(l)
    return lengths
```

**Comment by BlackPianoCat** [comment]
You are referred to this function `get_chromosome_lengths()` on `load_HiC.py`?

**Comment by seanpatrickmoran** [comment]
It's currently a work in progress. For the manuscript, we changed alot to remove wasteful computation. We're still debugging this, so the older version I'm not too clear about is still used as the main deployment. @dmcbffeng worked on the current running version of StripeCaller, maybe he can comment.

Back to your issue, I you need to use a hg38 size file, not fasta. Here's IGV's, [https://github.com/igvteam/igv/blob/master/genomes/sizes/hg38.chrom.sizes](url). 

change arguement reference_genome to point to the hg38 chrom size file when you call stripe_caller_all(), this may fix the problem.

**Comment by BlackPianoCat** [comment]
> Back to your issue, I think you need to use a hg38 size file, not fasta. Here's IGV's, [https://github.com/igvteam/igv/blob/master/genomes/sizes/hg38.chrom.sizes](url).

Maybe I wasn't clear, the input for this reference genome was your h38 file on your repo, and it showed me the error in the previous comment.

**Comment by seanpatrickmoran** [comment]
Sure, thanks for your comment.

I looked into this and found that this exception is raised when no stripe candidates pass the test for statistical significance. Therefore when merging "overlapping peaks" by taking a min from a list, no min can be taken.

You may try to change the args to stripe_caller_all(), "stripe_width", "max_range", "resolution", and "window_size", as well as "threshold". I'll talk to Fan about patching a more descriptive error here. 

Again, this version is more of a placeholder and will be replaced with a different one soon.

**Comment by BlackPianoCat** [comment]
Ok, thank you very much for your fast help. I am looking forward to see the final version of your repository (since it looks like a useful tool and I cannot find many stripe callers). I will check it again the next days and I hope that I will have a result.
